<?php

namespace Database\Seeders;

use App\Modules\SuperAdmin\Domain\Models\School;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class SchoolTrackSchoolsSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            [
                'name' => 'Lycée d\'Excellence de Dakar',
                'code' => 'ACAD-LED01',
                'type' => 'Lycée d\'Excellence',
                'sector' => 'Public / Conventionné',
                'is_bilingual' => true,
                'language_regime' => 'Bilingue (Français / Anglais)',
                'day_start_time' => '08:00:00',
                'day_end_time' => '17:00:00',
                'status' => 'actif',
                'plan_name' => 'Enterprise',
                'students_count' => 1250,
                'location' => 'Point E, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'contact@lycee-excellence.sn',
                'contact_phone' => '+221 33 825 40 10',
                'founded_date' => Carbon::parse('1998-09-15'),
                'slogan' => 'L\'excellence au service du leadership africain',
                'latitude' => 14.6980,
                'longitude' => -17.4580,
                'description' => 'Établissement de référence en Afrique de l\'Ouest combinant rigueur académique, pôle d\'excellence scientifique et accompagnement vers les plus prestigieuses universités mondiales.',
                'levels' => ['Collège', 'Lycée', 'Classes Préparatoires'],
                'tags' => ['Top 5% Régional', 'Pôle STEM', 'Bilingue', 'Internat', 'Excellence'],
                'facilities' => [
                    'laboratoire' => true,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => true,
                ],
                'gallery_paths' => [
                    'school_catalog/1CPIy8pM4PnhTrMm2qzw8YQ81WsQSR2HrCF7Cqmm.jpg',
                    'school_catalog/Ltoq5VXCEEXtHvX3KpJkFe8v0NsDSNK9Y1j1s8PV.jpg',
                    'school_catalog/GWlKWImtLefeCsnKxza3MNNR77z4FvlbRkv1ZKrS.jpg',
                ],
                'catalog_paths' => [
                    'school_catalog/1CPIy8pM4PnhTrMm2qzw8YQ81WsQSR2HrCF7Cqmm.jpg',
                ],
                'logo_url' => '/storage/logos/pending/5uLaZtuH9x7DpIUE3wmCZsK6I17xaY5utiBEkMBb.jpg',
            ],
            [
                'name' => 'Prestige International Academy',
                'code' => 'ACAD-PIA02',
                'type' => 'Académie Internationale',
                'sector' => 'Privé International',
                'is_bilingual' => true,
                'language_regime' => 'Immersion Anglaise & Française',
                'day_start_time' => '08:15:00',
                'day_end_time' => '16:30:00',
                'status' => 'actif',
                'plan_name' => 'Enterprise',
                'students_count' => 980,
                'location' => 'Les Almadies, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'admissions@prestige-academy.sn',
                'contact_phone' => '+221 33 869 12 00',
                'founded_date' => Carbon::parse('2005-09-01'),
                'slogan' => 'Empowering Tomorrow\'s Global Leaders',
                'latitude' => 14.7432,
                'longitude' => -17.5160,
                'description' => 'Campus moderne face à l\'océan aux Almadies. Programme Baccalauréat International (IB) et cursus Cambridge, infrastructures sportives et artistiques de rang mondial.',
                'levels' => ['Maternelle', 'Primaire', 'Collège', 'High School (IB)'],
                'tags' => ['Verified Institution', 'IB World School', 'Cambridge', 'Robotique', 'Sports Élite'],
                'facilities' => [
                    'laboratoire' => true,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => true,
                ],
                'gallery_paths' => [
                    'school_catalog/GWlKWImtLefeCsnKxza3MNNR77z4FvlbRkv1ZKrS.jpg',
                    'school_catalog/n69jIKMtKpRxc3g1DdChp1hAjrNGEblPDEOCoJJK.png',
                ],
                'catalog_paths' => [
                    'school_catalog/GWlKWImtLefeCsnKxza3MNNR77z4FvlbRkv1ZKrS.jpg',
                ],
                'logo_url' => '/storage/logos/Be4yxJullvBnkd7PC8x78TiK0lmFGXnqJTdkuiJd.png',
            ],
            [
                'name' => 'Groupe Scolaire Horizon',
                'code' => 'ACAD-GSH03',
                'type' => 'Groupe Scolaire',
                'sector' => 'Privé Laïc',
                'is_bilingual' => false,
                'language_regime' => 'Français avec renforcement Anglais',
                'day_start_time' => '07:45:00',
                'day_end_time' => '17:15:00',
                'status' => 'actif',
                'plan_name' => 'Premium',
                'students_count' => 1420,
                'location' => 'Mermoz-Pyrotechnie, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'contact@gshorizon.sn',
                'contact_phone' => '+221 33 860 77 88',
                'founded_date' => Carbon::parse('2010-10-04'),
                'slogan' => 'Construisons l\'avenir dès aujourd\'hui',
                'latitude' => 14.7110,
                'longitude' => -17.4720,
                'description' => 'Établissement moderne reconnu pour son taux de réussite de 98% au BFEM et Baccalauréat. Encadrement personnalisé et vie associative riche.',
                'levels' => ['Primaire', 'Collège', 'Lycée'],
                'tags' => ['Taux Bac 98%', 'Suivi Personnalisé', 'Laboratoires Numériques', 'Bus Scolaire'],
                'facilities' => [
                    'laboratoire' => true,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => false,
                ],
                'gallery_paths' => [
                    'school_catalog/Ltoq5VXCEEXtHvX3KpJkFe8v0NsDSNK9Y1j1s8PV.jpg',
                    'school_catalog/ekWphpxRu7GIGDDfewnJtnooudPGKjSxOXP0QOrp.jpg',
                ],
                'catalog_paths' => [
                    'school_catalog/Ltoq5VXCEEXtHvX3KpJkFe8v0NsDSNK9Y1j1s8PV.jpg',
                ],
                'logo_url' => '/storage/logos/DZoMq2fgKxEvvZYCScYrqna65Y4TKO5nEzQEb1xZ.png',
            ],
            [
                'name' => 'Lighthouse Science College',
                'code' => 'ACAD-LSC04',
                'type' => 'Collège & Lycée Scientifique',
                'sector' => 'Privé',
                'is_bilingual' => true,
                'language_regime' => 'Bilingue',
                'day_start_time' => '08:00:00',
                'day_end_time' => '17:00:00',
                'status' => 'actif',
                'plan_name' => 'Premium',
                'students_count' => 640,
                'location' => 'Fann Résidence, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'info@lighthouse-college.sn',
                'contact_phone' => '+221 33 824 15 15',
                'founded_date' => Carbon::parse('2015-09-10'),
                'slogan' => 'Where Curiosity Meets Innovation',
                'latitude' => 14.6910,
                'longitude' => -17.4680,
                'description' => 'Institut dédié aux sciences expérimentales, aux technologies et aux mathématiques appliquées avec clubs d\'astronomie et de robotique.',
                'levels' => ['Collège', 'Lycée'],
                'tags' => ['Top STEM', 'Robotique Lab', 'Smart Classrooms', 'Olympiades'],
                'facilities' => [
                    'laboratoire' => true,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => false,
                ],
                'gallery_paths' => [
                    'school_catalog/n69jIKMtKpRxc3g1DdChp1hAjrNGEblPDEOCoJJK.png',
                    'school_catalog/gAVQXAXAJ89Z3yDp9NHHeE0ukQWZtzJfHAZSTOTe.png',
                ],
                'catalog_paths' => [
                    'school_catalog/n69jIKMtKpRxc3g1DdChp1hAjrNGEblPDEOCoJJK.png',
                ],
                'logo_url' => '/storage/logos/pending/8LYXcTdNYuCR5a4G2hYKTOtEs3wyHapwdefUSeGo.jpg',
            ],
            [
                'name' => 'Horizon Preparatory School',
                'code' => 'ACAD-HPS05',
                'type' => 'École Préparatoire & Primaire',
                'sector' => 'Privé Bilingue',
                'is_bilingual' => true,
                'language_regime' => 'Bilingue Anglais-Français',
                'day_start_time' => '08:00:00',
                'day_end_time' => '15:30:00',
                'status' => 'actif',
                'plan_name' => 'Starter',
                'students_count' => 450,
                'location' => 'Ngor Virage, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'direction@horizon-prep.sn',
                'contact_phone' => '+221 33 820 05 05',
                'founded_date' => Carbon::parse('2018-01-15'),
                'slogan' => 'Nurturing Young Minds to Greatness',
                'latitude' => 14.7520,
                'longitude' => -17.5180,
                'description' => 'Pédagogie active axée sur l\'autonomie, les arts plastiques, le codage précoce et l\'apprentissage précoce des langues.',
                'levels' => ['Maternelle', 'Primaire'],
                'tags' => ['Pédagogie Active', 'Arts & Musique', 'Classes Réduites', 'Jardin Écologique'],
                'facilities' => [
                    'laboratoire' => false,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => false,
                ],
                'gallery_paths' => [
                    'school_catalog/ekWphpxRu7GIGDDfewnJtnooudPGKjSxOXP0QOrp.jpg',
                    'school_catalog/1CPIy8pM4PnhTrMm2qzw8YQ81WsQSR2HrCF7Cqmm.jpg',
                ],
                'catalog_paths' => [
                    'school_catalog/ekWphpxRu7GIGDDfewnJtnooudPGKjSxOXP0QOrp.jpg',
                ],
                'logo_url' => '/storage/logos/pending/5uLaZtuH9x7DpIUE3wmCZsK6I17xaY5utiBEkMBb.jpg',
            ],
            [
                'name' => 'Complexe International Sainte-Marie',
                'code' => 'ACAD-CISM06',
                'type' => 'Complexe Scolaire Catholique',
                'sector' => 'Privé Catholique',
                'is_bilingual' => false,
                'language_regime' => 'Français avec LV1 Anglais / LV2 Espagnol',
                'day_start_time' => '07:30:00',
                'day_end_time' => '17:00:00',
                'status' => 'actif',
                'plan_name' => 'Enterprise',
                'students_count' => 1800,
                'location' => 'Plateau, Dakar, Sénégal',
                'city' => 'Dakar',
                'country' => 'Sénégal',
                'contact_email' => 'contact@stemarie-dakar.org',
                'contact_phone' => '+221 33 821 34 50',
                'founded_date' => Carbon::parse('1965-10-01'),
                'slogan' => 'Foi, Savoir et Fraternité',
                'latitude' => 14.6710,
                'longitude' => -17.4330,
                'description' => 'Institution centenaire renommée pour sa discipline, son cadre d\'études privilégié au cœur de Dakar et ses diplômés d\'exception.',
                'levels' => ['Primaire', 'Collège', 'Lycée'],
                'tags' => ['Tradition d\'Excellence', 'Discipline', 'Chœur & Orchestre', 'Centre Documentaire'],
                'facilities' => [
                    'laboratoire' => true,
                    'informatique' => true,
                    'sport' => true,
                    'cantine' => true,
                    'bibliotheque' => true,
                    'infirmerie' => true,
                    'transport' => true,
                    'piscine' => false,
                ],
                'gallery_paths' => [
                    'school_catalog/GWlKWImtLefeCsnKxza3MNNR77z4FvlbRkv1ZKrS.jpg',
                    'school_catalog/Ltoq5VXCEEXtHvX3KpJkFe8v0NsDSNK9Y1j1s8PV.jpg',
                ],
                'catalog_paths' => [
                    'school_catalog/GWlKWImtLefeCsnKxza3MNNR77z4FvlbRkv1ZKrS.jpg',
                ],
                'logo_url' => '/storage/logos/Be4yxJullvBnkd7PC8x78TiK0lmFGXnqJTdkuiJd.png',
            ],
        ];

        foreach ($schools as $schoolData) {
            School::updateOrCreate(
                ['code' => $schoolData['code']],
                $schoolData
            );
        }
    }
}
